version: '3.8' # Убедитесь, что вы используете поддерживаемую версию Docker Compose

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data # Используйте более описательное имя тома
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql

      
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080" # Исправьте синтаксис портов, добавив кавычки вокруг номера порта

volumes:
  db_data: # Определите том для хранения данных базы данных